export const mockApiResponse = {
  total_count: 12187,
  incomplete_results: false,
  items: [
    {
      login: "abcd",
      id: 58120,
      node_id: "MDQ6VXNlcjU4MTIw",
      avatar_url: "https://avatars.githubusercontent.com/u/58120?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/abcd",
      html_url: "https://github.com/abcd",
      followers_url: "https://api.github.com/users/abcd/followers",
      following_url: "https://api.github.com/users/abcd/following{/other_user}",
      gists_url: "https://api.github.com/users/abcd/gists{/gist_id}",
      starred_url: "https://api.github.com/users/abcd/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/abcd/subscriptions",
      organizations_url: "https://api.github.com/users/abcd/orgs",
      repos_url: "https://api.github.com/users/abcd/repos",
      events_url: "https://api.github.com/users/abcd/events{/privacy}",
      received_events_url: "https://api.github.com/users/abcd/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "ildoonet",
      id: 1115758,
      node_id: "MDQ6VXNlcjExMTU3NTg=",
      avatar_url: "https://avatars.githubusercontent.com/u/1115758?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ildoonet",
      html_url: "https://github.com/ildoonet",
      followers_url: "https://api.github.com/users/ildoonet/followers",
      following_url:
        "https://api.github.com/users/ildoonet/following{/other_user}",
      gists_url: "https://api.github.com/users/ildoonet/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/ildoonet/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ildoonet/subscriptions",
      organizations_url: "https://api.github.com/users/ildoonet/orgs",
      repos_url: "https://api.github.com/users/ildoonet/repos",
      events_url: "https://api.github.com/users/ildoonet/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/ildoonet/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "ii17011701",
      id: 71713409,
      node_id: "MDQ6VXNlcjcxNzEzNDA5",
      avatar_url: "https://avatars.githubusercontent.com/u/71713409?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ii17011701",
      html_url: "https://github.com/ii17011701",
      followers_url: "https://api.github.com/users/ii17011701/followers",
      following_url:
        "https://api.github.com/users/ii17011701/following{/other_user}",
      gists_url: "https://api.github.com/users/ii17011701/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/ii17011701/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/ii17011701/subscriptions",
      organizations_url: "https://api.github.com/users/ii17011701/orgs",
      repos_url: "https://api.github.com/users/ii17011701/repos",
      events_url: "https://api.github.com/users/ii17011701/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/ii17011701/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "abcdabcd987",
      id: 2470081,
      node_id: "MDQ6VXNlcjI0NzAwODE=",
      avatar_url: "https://avatars.githubusercontent.com/u/2470081?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/abcdabcd987",
      html_url: "https://github.com/abcdabcd987",
      followers_url: "https://api.github.com/users/abcdabcd987/followers",
      following_url:
        "https://api.github.com/users/abcdabcd987/following{/other_user}",
      gists_url: "https://api.github.com/users/abcdabcd987/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/abcdabcd987/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/abcdabcd987/subscriptions",
      organizations_url: "https://api.github.com/users/abcdabcd987/orgs",
      repos_url: "https://api.github.com/users/abcdabcd987/repos",
      events_url: "https://api.github.com/users/abcdabcd987/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/abcdabcd987/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "abcdw",
      id: 1218615,
      node_id: "MDQ6VXNlcjEyMTg2MTU=",
      avatar_url: "https://avatars.githubusercontent.com/u/1218615?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/abcdw",
      html_url: "https://github.com/abcdw",
      followers_url: "https://api.github.com/users/abcdw/followers",
      following_url:
        "https://api.github.com/users/abcdw/following{/other_user}",
      gists_url: "https://api.github.com/users/abcdw/gists{/gist_id}",
      starred_url: "https://api.github.com/users/abcdw/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/abcdw/subscriptions",
      organizations_url: "https://api.github.com/users/abcdw/orgs",
      repos_url: "https://api.github.com/users/abcdw/repos",
      events_url: "https://api.github.com/users/abcdw/events{/privacy}",
      received_events_url: "https://api.github.com/users/abcdw/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "gradoally",
      id: 138923633,
      node_id: "O_kgDOCEfOcQ",
      avatar_url: "https://avatars.githubusercontent.com/u/138923633?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/gradoally",
      html_url: "https://github.com/gradoally",
      followers_url: "https://api.github.com/users/gradoally/followers",
      following_url:
        "https://api.github.com/users/gradoally/following{/other_user}",
      gists_url: "https://api.github.com/users/gradoally/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/gradoally/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/gradoally/subscriptions",
      organizations_url: "https://api.github.com/users/gradoally/orgs",
      repos_url: "https://api.github.com/users/gradoally/repos",
      events_url: "https://api.github.com/users/gradoally/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/gradoally/received_events",
      type: "Organization",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "nishanchettri",
      id: 35814272,
      node_id: "MDQ6VXNlcjM1ODE0Mjcy",
      avatar_url: "https://avatars.githubusercontent.com/u/35814272?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/nishanchettri",
      html_url: "https://github.com/nishanchettri",
      followers_url: "https://api.github.com/users/nishanchettri/followers",
      following_url:
        "https://api.github.com/users/nishanchettri/following{/other_user}",
      gists_url: "https://api.github.com/users/nishanchettri/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/nishanchettri/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/nishanchettri/subscriptions",
      organizations_url: "https://api.github.com/users/nishanchettri/orgs",
      repos_url: "https://api.github.com/users/nishanchettri/repos",
      events_url: "https://api.github.com/users/nishanchettri/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/nishanchettri/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "ABCD-STUDY",
      id: 16213687,
      node_id: "MDEyOk9yZ2FuaXphdGlvbjE2MjEzNjg3",
      avatar_url: "https://avatars.githubusercontent.com/u/16213687?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ABCD-STUDY",
      html_url: "https://github.com/ABCD-STUDY",
      followers_url: "https://api.github.com/users/ABCD-STUDY/followers",
      following_url:
        "https://api.github.com/users/ABCD-STUDY/following{/other_user}",
      gists_url: "https://api.github.com/users/ABCD-STUDY/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/ABCD-STUDY/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/ABCD-STUDY/subscriptions",
      organizations_url: "https://api.github.com/users/ABCD-STUDY/orgs",
      repos_url: "https://api.github.com/users/ABCD-STUDY/repos",
      events_url: "https://api.github.com/users/ABCD-STUDY/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/ABCD-STUDY/received_events",
      type: "Organization",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "abcd567a",
      id: 28452511,
      node_id: "MDQ6VXNlcjI4NDUyNTEx",
      avatar_url: "https://avatars.githubusercontent.com/u/28452511?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/abcd567a",
      html_url: "https://github.com/abcd567a",
      followers_url: "https://api.github.com/users/abcd567a/followers",
      following_url:
        "https://api.github.com/users/abcd567a/following{/other_user}",
      gists_url: "https://api.github.com/users/abcd567a/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/abcd567a/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/abcd567a/subscriptions",
      organizations_url: "https://api.github.com/users/abcd567a/orgs",
      repos_url: "https://api.github.com/users/abcd567a/repos",
      events_url: "https://api.github.com/users/abcd567a/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/abcd567a/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "abcdan",
      id: 15849319,
      node_id: "MDQ6VXNlcjE1ODQ5MzE5",
      avatar_url: "https://avatars.githubusercontent.com/u/15849319?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/abcdan",
      html_url: "https://github.com/abcdan",
      followers_url: "https://api.github.com/users/abcdan/followers",
      following_url:
        "https://api.github.com/users/abcdan/following{/other_user}",
      gists_url: "https://api.github.com/users/abcdan/gists{/gist_id}",
      starred_url: "https://api.github.com/users/abcdan/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/abcdan/subscriptions",
      organizations_url: "https://api.github.com/users/abcdan/orgs",
      repos_url: "https://api.github.com/users/abcdan/repos",
      events_url: "https://api.github.com/users/abcdan/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/abcdan/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "abcdsds",
      id: 50533198,
      node_id: "MDQ6VXNlcjUwNTMzMTk4",
      avatar_url: "https://avatars.githubusercontent.com/u/50533198?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/abcdsds",
      html_url: "https://github.com/abcdsds",
      followers_url: "https://api.github.com/users/abcdsds/followers",
      following_url:
        "https://api.github.com/users/abcdsds/following{/other_user}",
      gists_url: "https://api.github.com/users/abcdsds/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/abcdsds/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/abcdsds/subscriptions",
      organizations_url: "https://api.github.com/users/abcdsds/orgs",
      repos_url: "https://api.github.com/users/abcdsds/repos",
      events_url: "https://api.github.com/users/abcdsds/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/abcdsds/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "karaok1",
      id: 17222122,
      node_id: "MDQ6VXNlcjE3MjIyMTIy",
      avatar_url: "https://avatars.githubusercontent.com/u/17222122?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/karaok1",
      html_url: "https://github.com/karaok1",
      followers_url: "https://api.github.com/users/karaok1/followers",
      following_url:
        "https://api.github.com/users/karaok1/following{/other_user}",
      gists_url: "https://api.github.com/users/karaok1/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/karaok1/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/karaok1/subscriptions",
      organizations_url: "https://api.github.com/users/karaok1/orgs",
      repos_url: "https://api.github.com/users/karaok1/repos",
      events_url: "https://api.github.com/users/karaok1/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/karaok1/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "ABcDexter",
      id: 7236257,
      node_id: "MDQ6VXNlcjcyMzYyNTc=",
      avatar_url: "https://avatars.githubusercontent.com/u/7236257?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ABcDexter",
      html_url: "https://github.com/ABcDexter",
      followers_url: "https://api.github.com/users/ABcDexter/followers",
      following_url:
        "https://api.github.com/users/ABcDexter/following{/other_user}",
      gists_url: "https://api.github.com/users/ABcDexter/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/ABcDexter/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ABcDexter/subscriptions",
      organizations_url: "https://api.github.com/users/ABcDexter/orgs",
      repos_url: "https://api.github.com/users/ABcDexter/repos",
      events_url: "https://api.github.com/users/ABcDexter/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/ABcDexter/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "abcdsxg",
      id: 20315934,
      node_id: "MDQ6VXNlcjIwMzE1OTM0",
      avatar_url: "https://avatars.githubusercontent.com/u/20315934?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/abcdsxg",
      html_url: "https://github.com/abcdsxg",
      followers_url: "https://api.github.com/users/abcdsxg/followers",
      following_url:
        "https://api.github.com/users/abcdsxg/following{/other_user}",
      gists_url: "https://api.github.com/users/abcdsxg/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/abcdsxg/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/abcdsxg/subscriptions",
      organizations_url: "https://api.github.com/users/abcdsxg/orgs",
      repos_url: "https://api.github.com/users/abcdsxg/repos",
      events_url: "https://api.github.com/users/abcdsxg/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/abcdsxg/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "mridul0098",
      id: 92113512,
      node_id: "U_kgDOBX2KaA",
      avatar_url: "https://avatars.githubusercontent.com/u/92113512?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/mridul0098",
      html_url: "https://github.com/mridul0098",
      followers_url: "https://api.github.com/users/mridul0098/followers",
      following_url:
        "https://api.github.com/users/mridul0098/following{/other_user}",
      gists_url: "https://api.github.com/users/mridul0098/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/mridul0098/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/mridul0098/subscriptions",
      organizations_url: "https://api.github.com/users/mridul0098/orgs",
      repos_url: "https://api.github.com/users/mridul0098/repos",
      events_url: "https://api.github.com/users/mridul0098/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/mridul0098/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "abcdesktopio",
      id: 77065873,
      node_id: "MDEyOk9yZ2FuaXphdGlvbjc3MDY1ODcz",
      avatar_url: "https://avatars.githubusercontent.com/u/77065873?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/abcdesktopio",
      html_url: "https://github.com/abcdesktopio",
      followers_url: "https://api.github.com/users/abcdesktopio/followers",
      following_url:
        "https://api.github.com/users/abcdesktopio/following{/other_user}",
      gists_url: "https://api.github.com/users/abcdesktopio/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/abcdesktopio/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/abcdesktopio/subscriptions",
      organizations_url: "https://api.github.com/users/abcdesktopio/orgs",
      repos_url: "https://api.github.com/users/abcdesktopio/repos",
      events_url: "https://api.github.com/users/abcdesktopio/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/abcdesktopio/received_events",
      type: "Organization",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "abcdxo",
      id: 50033125,
      node_id: "MDQ6VXNlcjUwMDMzMTI1",
      avatar_url: "https://avatars.githubusercontent.com/u/50033125?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/abcdxo",
      html_url: "https://github.com/abcdxo",
      followers_url: "https://api.github.com/users/abcdxo/followers",
      following_url:
        "https://api.github.com/users/abcdxo/following{/other_user}",
      gists_url: "https://api.github.com/users/abcdxo/gists{/gist_id}",
      starred_url: "https://api.github.com/users/abcdxo/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/abcdxo/subscriptions",
      organizations_url: "https://api.github.com/users/abcdxo/orgs",
      repos_url: "https://api.github.com/users/abcdxo/repos",
      events_url: "https://api.github.com/users/abcdxo/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/abcdxo/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "abcdlsj",
      id: 37280497,
      node_id: "MDQ6VXNlcjM3MjgwNDk3",
      avatar_url: "https://avatars.githubusercontent.com/u/37280497?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/abcdlsj",
      html_url: "https://github.com/abcdlsj",
      followers_url: "https://api.github.com/users/abcdlsj/followers",
      following_url:
        "https://api.github.com/users/abcdlsj/following{/other_user}",
      gists_url: "https://api.github.com/users/abcdlsj/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/abcdlsj/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/abcdlsj/subscriptions",
      organizations_url: "https://api.github.com/users/abcdlsj/orgs",
      repos_url: "https://api.github.com/users/abcdlsj/repos",
      events_url: "https://api.github.com/users/abcdlsj/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/abcdlsj/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "JoseEduardoSalles",
      id: 70718000,
      node_id: "MDQ6VXNlcjcwNzE4MDAw",
      avatar_url: "https://avatars.githubusercontent.com/u/70718000?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/JoseEduardoSalles",
      html_url: "https://github.com/JoseEduardoSalles",
      followers_url: "https://api.github.com/users/JoseEduardoSalles/followers",
      following_url:
        "https://api.github.com/users/JoseEduardoSalles/following{/other_user}",
      gists_url:
        "https://api.github.com/users/JoseEduardoSalles/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/JoseEduardoSalles/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/JoseEduardoSalles/subscriptions",
      organizations_url: "https://api.github.com/users/JoseEduardoSalles/orgs",
      repos_url: "https://api.github.com/users/JoseEduardoSalles/repos",
      events_url:
        "https://api.github.com/users/JoseEduardoSalles/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/JoseEduardoSalles/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "ABCD-EDU",
      id: 102218575,
      node_id: "O_kgDOBhe7Tw",
      avatar_url: "https://avatars.githubusercontent.com/u/102218575?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ABCD-EDU",
      html_url: "https://github.com/ABCD-EDU",
      followers_url: "https://api.github.com/users/ABCD-EDU/followers",
      following_url:
        "https://api.github.com/users/ABCD-EDU/following{/other_user}",
      gists_url: "https://api.github.com/users/ABCD-EDU/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/ABCD-EDU/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ABCD-EDU/subscriptions",
      organizations_url: "https://api.github.com/users/ABCD-EDU/orgs",
      repos_url: "https://api.github.com/users/ABCD-EDU/repos",
      events_url: "https://api.github.com/users/ABCD-EDU/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/ABCD-EDU/received_events",
      type: "Organization",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "adzinzhalifunnas",
      id: 36525652,
      node_id: "MDQ6VXNlcjM2NTI1NjUy",
      avatar_url: "https://avatars.githubusercontent.com/u/36525652?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/adzinzhalifunnas",
      html_url: "https://github.com/adzinzhalifunnas",
      followers_url: "https://api.github.com/users/adzinzhalifunnas/followers",
      following_url:
        "https://api.github.com/users/adzinzhalifunnas/following{/other_user}",
      gists_url:
        "https://api.github.com/users/adzinzhalifunnas/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/adzinzhalifunnas/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/adzinzhalifunnas/subscriptions",
      organizations_url: "https://api.github.com/users/adzinzhalifunnas/orgs",
      repos_url: "https://api.github.com/users/adzinzhalifunnas/repos",
      events_url:
        "https://api.github.com/users/adzinzhalifunnas/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/adzinzhalifunnas/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "ABCDELabs",
      id: 121791716,
      node_id: "O_kgDOB0Jk5A",
      avatar_url: "https://avatars.githubusercontent.com/u/121791716?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/ABCDELabs",
      html_url: "https://github.com/ABCDELabs",
      followers_url: "https://api.github.com/users/ABCDELabs/followers",
      following_url:
        "https://api.github.com/users/ABCDELabs/following{/other_user}",
      gists_url: "https://api.github.com/users/ABCDELabs/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/ABCDELabs/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/ABCDELabs/subscriptions",
      organizations_url: "https://api.github.com/users/ABCDELabs/orgs",
      repos_url: "https://api.github.com/users/ABCDELabs/repos",
      events_url: "https://api.github.com/users/ABCDELabs/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/ABCDELabs/received_events",
      type: "Organization",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "abcdeepakr",
      id: 33338977,
      node_id: "MDQ6VXNlcjMzMzM4OTc3",
      avatar_url: "https://avatars.githubusercontent.com/u/33338977?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/abcdeepakr",
      html_url: "https://github.com/abcdeepakr",
      followers_url: "https://api.github.com/users/abcdeepakr/followers",
      following_url:
        "https://api.github.com/users/abcdeepakr/following{/other_user}",
      gists_url: "https://api.github.com/users/abcdeepakr/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/abcdeepakr/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/abcdeepakr/subscriptions",
      organizations_url: "https://api.github.com/users/abcdeepakr/orgs",
      repos_url: "https://api.github.com/users/abcdeepakr/repos",
      events_url: "https://api.github.com/users/abcdeepakr/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/abcdeepakr/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "lozn00",
      id: 14260426,
      node_id: "MDQ6VXNlcjE0MjYwNDI2",
      avatar_url: "https://avatars.githubusercontent.com/u/14260426?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/lozn00",
      html_url: "https://github.com/lozn00",
      followers_url: "https://api.github.com/users/lozn00/followers",
      following_url:
        "https://api.github.com/users/lozn00/following{/other_user}",
      gists_url: "https://api.github.com/users/lozn00/gists{/gist_id}",
      starred_url: "https://api.github.com/users/lozn00/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/lozn00/subscriptions",
      organizations_url: "https://api.github.com/users/lozn00/orgs",
      repos_url: "https://api.github.com/users/lozn00/repos",
      events_url: "https://api.github.com/users/lozn00/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/lozn00/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "abcdxyzk",
      id: 3094675,
      node_id: "MDQ6VXNlcjMwOTQ2NzU=",
      avatar_url: "https://avatars.githubusercontent.com/u/3094675?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/abcdxyzk",
      html_url: "https://github.com/abcdxyzk",
      followers_url: "https://api.github.com/users/abcdxyzk/followers",
      following_url:
        "https://api.github.com/users/abcdxyzk/following{/other_user}",
      gists_url: "https://api.github.com/users/abcdxyzk/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/abcdxyzk/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/abcdxyzk/subscriptions",
      organizations_url: "https://api.github.com/users/abcdxyzk/orgs",
      repos_url: "https://api.github.com/users/abcdxyzk/repos",
      events_url: "https://api.github.com/users/abcdxyzk/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/abcdxyzk/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "abcdaaaaaaaaa",
      id: 108553778,
      node_id: "U_kgDOBnhmMg",
      avatar_url: "https://avatars.githubusercontent.com/u/108553778?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/abcdaaaaaaaaa",
      html_url: "https://github.com/abcdaaaaaaaaa",
      followers_url: "https://api.github.com/users/abcdaaaaaaaaa/followers",
      following_url:
        "https://api.github.com/users/abcdaaaaaaaaa/following{/other_user}",
      gists_url: "https://api.github.com/users/abcdaaaaaaaaa/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/abcdaaaaaaaaa/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/abcdaaaaaaaaa/subscriptions",
      organizations_url: "https://api.github.com/users/abcdaaaaaaaaa/orgs",
      repos_url: "https://api.github.com/users/abcdaaaaaaaaa/repos",
      events_url: "https://api.github.com/users/abcdaaaaaaaaa/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/abcdaaaaaaaaa/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "abcdefg30",
      id: 7704140,
      node_id: "MDQ6VXNlcjc3MDQxNDA=",
      avatar_url: "https://avatars.githubusercontent.com/u/7704140?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/abcdefg30",
      html_url: "https://github.com/abcdefg30",
      followers_url: "https://api.github.com/users/abcdefg30/followers",
      following_url:
        "https://api.github.com/users/abcdefg30/following{/other_user}",
      gists_url: "https://api.github.com/users/abcdefg30/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/abcdefg30/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/abcdefg30/subscriptions",
      organizations_url: "https://api.github.com/users/abcdefg30/orgs",
      repos_url: "https://api.github.com/users/abcdefg30/repos",
      events_url: "https://api.github.com/users/abcdefg30/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/abcdefg30/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "abcdjdj",
      id: 4457834,
      node_id: "MDQ6VXNlcjQ0NTc4MzQ=",
      avatar_url: "https://avatars.githubusercontent.com/u/4457834?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/abcdjdj",
      html_url: "https://github.com/abcdjdj",
      followers_url: "https://api.github.com/users/abcdjdj/followers",
      following_url:
        "https://api.github.com/users/abcdjdj/following{/other_user}",
      gists_url: "https://api.github.com/users/abcdjdj/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/abcdjdj/starred{/owner}{/repo}",
      subscriptions_url: "https://api.github.com/users/abcdjdj/subscriptions",
      organizations_url: "https://api.github.com/users/abcdjdj/orgs",
      repos_url: "https://api.github.com/users/abcdjdj/repos",
      events_url: "https://api.github.com/users/abcdjdj/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/abcdjdj/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "FedDragon1",
      id: 91022167,
      node_id: "MDQ6VXNlcjkxMDIyMTY3",
      avatar_url: "https://avatars.githubusercontent.com/u/91022167?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/FedDragon1",
      html_url: "https://github.com/FedDragon1",
      followers_url: "https://api.github.com/users/FedDragon1/followers",
      following_url:
        "https://api.github.com/users/FedDragon1/following{/other_user}",
      gists_url: "https://api.github.com/users/FedDragon1/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/FedDragon1/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/FedDragon1/subscriptions",
      organizations_url: "https://api.github.com/users/FedDragon1/orgs",
      repos_url: "https://api.github.com/users/FedDragon1/repos",
      events_url: "https://api.github.com/users/FedDragon1/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/FedDragon1/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
    {
      login: "=========== LAST USER OF THIS PAGE ===========",
      id: 9335372,
      node_id: "MDQ6VXNlcjkzMzUzNzI=",
      avatar_url: "https://avatars.githubusercontent.com/u/9335372?v=4",
      gravatar_id: "",
      url: "https://api.github.com/users/abcdefgs0324",
      html_url: "https://github.com/abcdefgs0324",
      followers_url: "https://api.github.com/users/abcdefgs0324/followers",
      following_url:
        "https://api.github.com/users/abcdefgs0324/following{/other_user}",
      gists_url: "https://api.github.com/users/abcdefgs0324/gists{/gist_id}",
      starred_url:
        "https://api.github.com/users/abcdefgs0324/starred{/owner}{/repo}",
      subscriptions_url:
        "https://api.github.com/users/abcdefgs0324/subscriptions",
      organizations_url: "https://api.github.com/users/abcdefgs0324/orgs",
      repos_url: "https://api.github.com/users/abcdefgs0324/repos",
      events_url: "https://api.github.com/users/abcdefgs0324/events{/privacy}",
      received_events_url:
        "https://api.github.com/users/abcdefgs0324/received_events",
      type: "User",
      user_view_type: "public",
      site_admin: false,
      score: 1.0,
    },
  ],
};
